### ISSUE TITLE
Possible to extend to Git commit graph?

### ISSUE THREAD

**Issue by tennox** [usernamehw/vscode-autolink#1]
![image](https://user-images.githubusercontent.com/2084639/169317770-3d278681-0e58-4541-ad4f-4bf1316c51a5.png)

Love the extension and it would be even nicer if it would also apply to Git Graph text.

Is that possible?

**Comment by usernamehw** [comment]
Is this text inside a webview? It's not possible to access it from another extension. You should file a feature request at Git Graph.

**Comment by tennox** [comment]
While doing that I realized they already have that feature 😅🙈
