### ISSUE TITLE
Open link just by clicking

### ISSUE THREAD

**Issue by JenieX** [usernamehw/vscode-autolink#2]
Is it possible to make the link pattern clickable without holding `Alt`?

Thank you anyways for this neat extension and your other extensions as well. 😄

**Comment by usernamehw** [comment]
Maybe it should be a separate extension?

There is api to subscribe to event of `onDidChangeTextEditorSelection` which changes on every cursor change (typing or clicking), but it can also distinguish between keyboard and mouse event origin. And it won't work if you click on the place where cursor already is.

**Comment by JenieX** [comment]
> 

I know JavaScript but not familiar with VSC extensions and their methods yet, so I really can't comment on your question.
I also came across [this extension](https://marketplace.visualstudio.com/items?itemName=Fr43nk.seito-openfile) yesterday where it adds an option in context menu to trigger a function, if not possible to implement it without the `Alt`, maybe this is possible somehow.

**Comment by usernamehw** [comment]
I made a different extension for this feature. MS Marketplace has problems publishing right now. 

If you want you can download and install extension from `.vsix` file: 

https://open-vsx.org/extension/usernamehw/auto-open-link

**Comment by JenieX** [comment]
> I made a different extension for this feature. MS Marketplace has problems publishing right now.
> 
> If you want you can download and install extension from `.vsix` file:
> 
> https://open-vsx.org/extension/usernamehw/auto-open-link

Thank you very much, that is a better solution that what I expected, especially with the ability to match with regexp. 😄
